development:
  adapter: postgresql
  enconding: unicode
  database: tweet_bot_dev
  pool: 5
  timeout: 5000

test: &test
  adapter: postgresql
  enconding: unicode
  database: tweet_bot_test
  pool: 5
  timeout: 5000
